# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ConnectMyCar' do
    pod 'ReactiveCocoa', '2.5'
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'ConnectMyCarTests' do

end

